# Generated by Django 4.2.7 on 2023-11-22 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YourModelName',
            new_name='Adresses',
        ),
    ]
