# Generated by Django 4.2.7 on 2023-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_adresses_square'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adresses',
            old_name='adress',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='adresses',
            name='longitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
