# Generated by Django 4.2.7 on 2023-11-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_rename_adress_adresses_latitude_adresses_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresses',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='adresses',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
